import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {

    FETCH_USER_BY_ID: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID`,
    FETCH_USER_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_REQUEST`,
    FETCH_USER_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_SUCCESS`,
    FETCH_USER_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_FAILURE`,

    FETCH_USER_DETAILS: `${STATE_REDUCER_KEY}/FETCH_USER_DETAILS`,
    FETCH_USER_DETAILS_REQUEST: `${STATE_REDUCER_KEY}/FETCH_USER_DETAILS_REQUEST`,
    FETCH_USER_DETAILS_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_USER_DETAILS_SUCCESS`,
    FETCH_USER_DETAILS_FAILURE: `${STATE_REDUCER_KEY}/FETCH_USER_DETAILS_FAILURE`,

    SET_USERS: `${STATE_REDUCER_KEY}/SET_USERS`,
    FETCH_USERS: `${STATE_REDUCER_KEY}/FETCH_USERS`

};


export const updateProfile = createAction(ACTION_TYPES.FETCH_USER_BY_ID);

export const loadUsers = createAction(ACTION_TYPES.FETCH_USER_DETAILS);
export const setUsers = createAction(ACTION_TYPES.SET_USERS);


