import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {


    FETCH_USER_BY_ID: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID`,
    FETCH_USER_BY_ID_REQUEST: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_REQUEST`,
    FETCH_USER_BY_ID_SUCCESS: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_SUCCESS`,
    FETCH_USER_BY_ID_FAILURE: `${STATE_REDUCER_KEY}/FETCH_USER_BY_ID_FAILURE`,

    UPLOAD_PROFILE_IMAGE: `${STATE_REDUCER_KEY}/UPLOAD_PROFILE_IMAGE`,
    UPLOAD_PROFILE_IMAGE_REQUEST: `${STATE_REDUCER_KEY}/UPLOAD_PROFILE_IMAGE_REQUEST`,
    UPLOAD_PROFILE_IMAGE_SUCCESS: `${STATE_REDUCER_KEY}/UPLOAD_PROFILE_IMAGE_SUCCESS`,
    UPLOAD_PROFILE_IMAGE_FAILURE: `${STATE_REDUCER_KEY}/UPLOAD_PROFILE_IMAGE_FAILURE`,

    CHANGE_PASSWORD: `${STATE_REDUCER_KEY}/CHANGE_PASSWORD`,
    CHANGE_PASSWORD_REQUEST: `${STATE_REDUCER_KEY}/CHANGE_PASSWORD_REQUEST`,
    CHANGE_PASSWORD_SUCCESS: `${STATE_REDUCER_KEY}/CHANGE_PASSWORD_SUCCESS`,
    CHANGE_PASSWORD_FAILURE: `${STATE_REDUCER_KEY}/CHANGE_PASSWORD_FAILURE`

};

export const uploadProfileImage = createAction(ACTION_TYPES.UPLOAD_PROFILE_IMAGE);
export const updateProfile = createAction(ACTION_TYPES.FETCH_USER_BY_ID);
export const changePassowrd = createAction(ACTION_TYPES.CHANGE_PASSWORD);


