export const STATE_REDUCER_KEY = "profile";

export const PROFILE_PATH = {
    EDIT_PROFILE: "EDIT_PROFILE",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    SETTINGS: "SETTINGS",
    SUBSCRIPTION: "SUBSCRIPTION"

};
